name: Purple AI Updater 
on: 
  workflow_dispatch: 
steps: 
  - uses: actions/checkout@v3
  - uses: actions/setup-node@v3 
    with: 
      node-version: 16 
  - name: Install dependencies
    run: npm ci 
  - name: Run Purple AI Updater script 
    run: node updater/purpleAIUpdater.js 