name: Purple AI Updater 
on: 
  workflow_dispatch: 
jobs: 
  purpleAIUpdater: 
    runs-on: ubuntu-latest
    environment: dev
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 
        with: 
          node-version: 16 
      - run: env
      - name: Install dependencies
        run: npm ci 
      - name: Set up environment variables
        run: | 
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo OPENAI_API_ENDPOINT=${{ secrets.OPENAI_API_ENDPOINT }} >> .env
          echo OPENAI_FLOW_ID=${{ secrets.OPENAI_FLOW_ID }} >> .env
          echo SCOPE"=${{ secrets.SCOPE }} >> .env
          echo GOOGLE_CLIENT_EMAIL"=${{ secrets.GOOGLE_CLIENT_EMAIL }} >> .env
          echo GOOGLE_PRIVATE_KEY"=${{ secrets.GOOGLE_PRIVATE_KEY }} >> .env
          echo GOOGLE_SHEET_ID"=${{ secrets.GOOGLE_SHEET_ID }} >> .env
      - name: Run Purple AI Updater script 
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: ${{ secrets.OPENAI_API_ENDPOINT }}
          OPENAI_FLOW_ID: ${{ secrets.OPENAI_FLOW_ID }}
          SCOPE: ${{ secrets.SCOPE }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: node updater/purpleAIUpdater.js 
